export { craftDataService, CraftDataService } from '@/services/craft-data.service'
export * from '@/services/migration.service'
export { migrateDatabase } from '@/services/database-migration.service'
export * from '@/services/ordem-servico.service'
export * from '@/services/analytics.service'
export * from '@/services/agendamento.service'
export { localCraftRepository, LocalCraftRepository } from '@/services/repository/local.repository'
export { supabaseCraftRepository, SupabaseCraftRepository } from '@/services/repository/supabase.repository'
export { createCraftRepository, getActivePersistenceLabel } from '@/services/repository/repository.factory'
export type { ICraftRepository, ISupabaseCraftRepository, CraftRepositoryKind } from '@/services/repository/types'
export { isSupabaseConfigured, getCraftPersistenceMode, getSupabaseClient } from '@/lib/supabase'
export { localAuthService, LocalAuthService, DEMO_CREDENTIALS, AUTH_STORAGE_KEY } from '@/services/auth/local-auth.service'
export * from '@/services/auth/permissions'
export type { IAuthService } from '@/services/auth/auth.types'
export { assinaturaService, AssinaturaService, ASSINATURA_STORAGE_KEY } from '@/services/assinatura/assinatura.service'
export * from '@/services/assinatura/plano-features'
export * from '@/services/relatorios.service'
export * from '@/services/comunicacao/comunicacao.service'
export { abrirWhatsAppWeb, buildWhatsAppUrl, normalizarTelefoneWhatsApp } from '@/services/comunicacao/whatsapp.service'
export * from '@/services/lembretes/lembretes.service'
export * from '@/services/portal-cliente/portal-cliente.service'
export * from '@/services/sync/sync-queue.service'
